/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'id' : bigint,
  'age' : bigint,
  'bmi' : number,
  'glucoseScore' : MetricScore,
  'diastolicBPScore' : MetricScore,
  'systolicBP' : bigint,
  'systolicBPScore' : MetricScore,
  'diastolicBP' : bigint,
  'glucose' : bigint,
  'overallRisk' : RiskLevel,
  'bmiScore' : MetricScore,
  'timestamp' : bigint,
  'patientName' : string,
  'ageScore' : MetricScore,
}
export interface MetricScore { 'value' : number, 'risk' : RiskLevel }
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface _SERVICE {
  'deleteAssessment' : ActorMethod<[bigint], undefined>,
  'getAllAssessments' : ActorMethod<[], Array<Assessment>>,
  'getAssessment' : ActorMethod<[bigint], Assessment>,
  'getRiskLevelCounts' : ActorMethod<
    [],
    { 'low' : bigint, 'high' : bigint, 'medium' : bigint }
  >,
  'submitAssessment' : ActorMethod<
    [string, bigint, number, bigint, bigint, bigint],
    Assessment
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];