/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const MetricScore = IDL.Record({
  'value' : IDL.Float64,
  'risk' : RiskLevel,
});
export const Assessment = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'glucoseScore' : MetricScore,
  'diastolicBPScore' : MetricScore,
  'systolicBP' : IDL.Nat,
  'systolicBPScore' : MetricScore,
  'diastolicBP' : IDL.Nat,
  'glucose' : IDL.Nat,
  'overallRisk' : RiskLevel,
  'bmiScore' : MetricScore,
  'timestamp' : IDL.Int,
  'patientName' : IDL.Text,
  'ageScore' : MetricScore,
});

export const idlService = IDL.Service({
  'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
  'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
  'getRiskLevelCounts' : IDL.Func(
      [],
      [IDL.Record({ 'low' : IDL.Nat, 'high' : IDL.Nat, 'medium' : IDL.Nat })],
      ['query'],
    ),
  'submitAssessment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat],
      [Assessment],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MetricScore = IDL.Record({ 'value' : IDL.Float64, 'risk' : RiskLevel });
  const Assessment = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'glucoseScore' : MetricScore,
    'diastolicBPScore' : MetricScore,
    'systolicBP' : IDL.Nat,
    'systolicBPScore' : MetricScore,
    'diastolicBP' : IDL.Nat,
    'glucose' : IDL.Nat,
    'overallRisk' : RiskLevel,
    'bmiScore' : MetricScore,
    'timestamp' : IDL.Int,
    'patientName' : IDL.Text,
    'ageScore' : MetricScore,
  });
  
  return IDL.Service({
    'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
    'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
    'getRiskLevelCounts' : IDL.Func(
        [],
        [IDL.Record({ 'low' : IDL.Nat, 'high' : IDL.Nat, 'medium' : IDL.Nat })],
        ['query'],
      ),
    'submitAssessment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat],
        [Assessment],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };