/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MetricScore {
    value: number;
    risk: RiskLevel;
}
export interface Assessment {
    id: bigint;
    age: bigint;
    bmi: number;
    glucoseScore: MetricScore;
    diastolicBPScore: MetricScore;
    systolicBP: bigint;
    systolicBPScore: MetricScore;
    diastolicBP: bigint;
    glucose: bigint;
    overallRisk: RiskLevel;
    bmiScore: MetricScore;
    timestamp: bigint;
    patientName: string;
    ageScore: MetricScore;
}
export enum RiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    deleteAssessment(id: bigint): Promise<void>;
    getAllAssessments(): Promise<Array<Assessment>>;
    getAssessment(id: bigint): Promise<Assessment>;
    getRiskLevelCounts(): Promise<{
        low: bigint;
        high: bigint;
        medium: bigint;
    }>;
    submitAssessment(patientName: string, age: bigint, bmi: number, systolicBP: bigint, diastolicBP: bigint, glucose: bigint): Promise<Assessment>;
}
import type { Assessment as _Assessment, MetricScore as _MetricScore, RiskLevel as _RiskLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteAssessment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssessment(arg0);
            return result;
        }
    }
    async getAllAssessments(): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssessment(arg0: bigint): Promise<Assessment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessment(arg0);
                return from_candid_Assessment_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessment(arg0);
            return from_candid_Assessment_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskLevelCounts(): Promise<{
        low: bigint;
        high: bigint;
        medium: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskLevelCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskLevelCounts();
            return result;
        }
    }
    async submitAssessment(arg0: string, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint, arg5: bigint): Promise<Assessment> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssessment(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Assessment_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssessment(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Assessment_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Assessment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assessment): Assessment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MetricScore_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricScore): MetricScore {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    bmi: number;
    glucoseScore: _MetricScore;
    diastolicBPScore: _MetricScore;
    systolicBP: bigint;
    systolicBPScore: _MetricScore;
    diastolicBP: bigint;
    glucose: bigint;
    overallRisk: _RiskLevel;
    bmiScore: _MetricScore;
    timestamp: bigint;
    patientName: string;
    ageScore: _MetricScore;
}): {
    id: bigint;
    age: bigint;
    bmi: number;
    glucoseScore: MetricScore;
    diastolicBPScore: MetricScore;
    systolicBP: bigint;
    systolicBPScore: MetricScore;
    diastolicBP: bigint;
    glucose: bigint;
    overallRisk: RiskLevel;
    bmiScore: MetricScore;
    timestamp: bigint;
    patientName: string;
    ageScore: MetricScore;
} {
    return {
        id: value.id,
        age: value.age,
        bmi: value.bmi,
        glucoseScore: from_candid_MetricScore_n4(_uploadFile, _downloadFile, value.glucoseScore),
        diastolicBPScore: from_candid_MetricScore_n4(_uploadFile, _downloadFile, value.diastolicBPScore),
        systolicBP: value.systolicBP,
        systolicBPScore: from_candid_MetricScore_n4(_uploadFile, _downloadFile, value.systolicBPScore),
        diastolicBP: value.diastolicBP,
        glucose: value.glucose,
        overallRisk: from_candid_RiskLevel_n6(_uploadFile, _downloadFile, value.overallRisk),
        bmiScore: from_candid_MetricScore_n4(_uploadFile, _downloadFile, value.bmiScore),
        timestamp: value.timestamp,
        patientName: value.patientName,
        ageScore: from_candid_MetricScore_n4(_uploadFile, _downloadFile, value.ageScore)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    risk: _RiskLevel;
}): {
    value: number;
    risk: RiskLevel;
} {
    return {
        value: value.value,
        risk: from_candid_RiskLevel_n6(_uploadFile, _downloadFile, value.risk)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assessment>): Array<Assessment> {
    return value.map((x)=>from_candid_Assessment_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
